<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class InsertDataDummyToMasterUsers extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('master_users', function (Blueprint $table) {
            //
        });
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('master_users')->insert([
            [
                'id' => 1,
                'nip' => 123,
                'name' => 'Dummy Admin',
                'dob' => '2000/02/20',
                'address' => 'Uranus',
                'phone_number' => '1234567890',
                'gender' => 'Laki-laki',
                'email' => 'admin@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 6,
                'position_id' => 3,
                'role_id' => 1
            ],
            [
                'id' => 2,
                'nip' => 456,
                'name' => 'Dummy Staff',
                'dob' => '2000/12/20',
                'address' => 'Saturnus',
                'phone_number' => '0987654321',
                'gender' => 'Perempuan',
                'email' => 'staff@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultP.png',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 1,
                'position_id' => 4,
                'role_id' => 2
            ],
            [
                'id' => 3,
                'nip' => 789,
                'name' => 'Test Dummy',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 1,
                'position_id' => 4,
                'role_id' => 2
            ],
            [
                'id' => 4,
                'nip' => 111,
                'name' => 'Staff Devtech',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 1,
                'position_id' => 11,
                'role_id' => 2
            ],
            [
                'id' => 5,
                'nip' => 112,
                'name' => 'Staff Sales',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 5,
                'position_id' => 11,
                'role_id' => 2
            ],
            [
                'id' => 6,
                'nip' => 113,
                'name' => 'Staff Marketing',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 6,
                'position_id' => 11,
                'role_id' => 2
            ],
            [
                'id' => 7,
                'nip' => 114,
                'name' => 'Staff Operation',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 2,
                'position_id' => 11,
                'role_id' => 2
            ],
            [
                'id' => 8,
                'nip' => 115,
                'name' => 'Staff QC',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 3,
                'position_id' => 11,
                'role_id' => 2
            ],
            [
                'id' => 9,
                'nip' => 116,
                'name' => 'Staff Academic',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 4,
                'position_id' => 11,
                'role_id' => 2
            ],
            [
                'id' => 10,
                'nip' => 117,
                'name' => 'One Ring CEO',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 7,
                'position_id' => 1,
                'role_id' => 1
            ],
            [
                'id' => 11,
                'nip' => 118,
                'name' => 'One Ring President',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 7,
                'position_id' => 2,
                'role_id' => 1
            ],
            [
                'id' => 12,
                'nip' => 211,
                'name' => 'Chief Devtech',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 1,
                'position_id' => 4,
                'role_id' => 2
            ],
            [
                'id' => 13,
                'nip' => 212,
                'name' => 'Chief Business',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 6,
                'position_id' => 6,
                'role_id' => 2
            ],
            [
                'id' => 14,
                'nip' => 213,
                'name' => 'Chief Sales',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 5,
                'position_id' => 10,
                'role_id' => 2
            ],
            [
                'id' => 15,
                'nip' => 214,
                'name' => 'Chief Prduction',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 3,
                'position_id' => 5,
                'role_id' => 2
            ],
            [
                'id' => 16,
                'nip' => 215,
                'name' => 'Chief Operation',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 2,
                'position_id' => 7,
                'role_id' => 2
            ],
            [
                'id' => 17,
                'nip' => 216,
                'name' => 'Chief QC',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 3,
                'position_id' => 8,
                'role_id' => 2
            ],
            [
                'id' => 18,
                'nip' => 217,
                'name' => 'Chief Academic',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 4,
                'position_id' => 9,
                'role_id' => 2
            ],
            [
                'id' => 19,
                'nip' => 222,
                'name' => 'Chief Data(Mang)',
                'dob' => '2000/12/20',
                'address' => 'Venus',
                'phone_number' => '0987654321',
                'gender' => 'Laki-laki',
                'email' => 'olaf@dummy.com',
                'password' => Hash::make('cerebrum'),
                'profile_photo' => 'defaultL.jpg',
                'employee_status' => 'Tetap',
                'employee_type' => 'Fulltime',
                'status' => 'Aktif',
                'start_work_date' => '2021/01/01',
                'yearly_leave_remaining' => 12,
                'division_id' => 7,
                'position_id' => 3,
                'role_id' => 1
            ]
            ]);
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('master_users', function (Blueprint $table) {
            //
        });
    }
}
